### ISSUE TITLE
Verify that all test cases are executed

### ISSUE THREAD

**Issue by mthuurne** [twisted/pydoctor#245]
my concern is to not end up with accidentally not installing the extension and then the test is always skipped... like we had with twisted tests and pydoctor not being installed.

To mitigate this, I am using codecov and a separate target that makes sure the tests code have 100%  coverage... if someone some tests are always skipped then the coverage will no longer be 100% and end up with a red flag :)

_Originally posted by @adiroiban in https://github.com/twisted/pydoctor/pull/243#discussion_r514645848_

**Comment by tristanlatr** [comment]
I think all test cases are executed.

**Comment by adiroiban** [comment]
To get a report if a test is not executed as part of the CI...hence there is no coverage for it.


Create codecov.yaml

```
codecov:
  require_ci_to_pass: yes
  notify:
    # We have at least 8 unit test builds in GitHub Actions + system tests
    after_n_builds: 10
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 95..100
  status:
    patch:
      default:
        # Fail if a PR doesn't have 100% coverge.
        target: 100%
    project:
      default:
        # Temporary allow for a bit of slack in overall code coverage due to
        # swinging coverage that is not triggered by changes in a PR.
        # See: https://twistedmatrix.com/trac/ticket/10170
        threshold: 0.02%
      tests:
        target: 100%
        paths:
          - "pydoctor/tests*"

# We don't want to receive general PR comments about coverage.
# We have the commit status checks and that should be enough.
# And we also enable annotation below.
# See https://docs.codecov.io/docs/pull-request-comments
comment: false

# See https://docs.codecov.io/docs/github-checks
github_checks:
  # We want codecov to send inline PR comments for missing coverage.
  annotations: true

```

but we need to update .coveragerc

```diff
[run]
branch = True
omit =
    pydoctor/sphinx_ext/*
-    pydoctor/test/*
    pydoctor/epydoc/sre_parse36.py
```
